### ISSUE TITLE
SF 5 Compatibility

### ISSUE THREAD

**Issue by JSmythSSG** [hshn/base64-encoded-file#18]
Hi is it possible to update it for Symfony 5 please?

**Comment by oleg-brizy** [comment]
A fork for SF 5 and php 7.4 (no backwards compatible)
https://github.com/bagrinsergiu/base64-encoded-file

_I just made the tests pass, haven't used it in a project yet (I'll do in a few days)_

**Comment by silverbackdan** [comment]
PR #19  raised to support all previous versions and SF5

**Comment by hshn** [comment]
released as [v2.1.0](https://packagist.org/packages/hshn/base64-encoded-file#v2.1.0)

thank you @silverbackdan
