### ISSUE TITLE
Symfony3 support

### ISSUE THREAD

**Issue by conradfr** [hshn/base64-encoded-file#3]
Due to the use of the ~2.x in composer.json you currently can't install this project within a Symfony3 project.

You could add "|~3.0" to version constraints on Symfony components to fix it (if nothing break).

May do a PR if I got the time.

**Comment by hshn** [comment]
Thank you for reporting!
I've added the suggested version constraint and released as `v1.2.0`.

For more information, please see https://github.com/hshn/base64-encoded-file/releases/tag/v1.2.0

**Comment by conradfr** [comment]
Great, thanks !
