### ISSUE TITLE
Support Symfony 6

### ISSUE THREAD

**Issue by odinns** [hshn/base64-encoded-file#30]
Hi there, we needed this package to support Symfony 6, so I forked and created a PR for you to merge.

https://github.com/hshn/base64-encoded-file/pull/29

Let me know if you need anything else from me for this.

Thanks, Odinn 😊

**Comment by hshn** [comment]
Hi Odinn, thank you for your PR!

The changes are released as [v4.1.0](https://github.com/hshn/base64-encoded-file/releases/tag/v4.1.0).
