### ISSUE TITLE
SF 4 compatibility ?

### ISSUE THREAD

**Issue by julienpillias** [hshn/base64-encoded-file#6]
Hi,

Is it possible to have a SF 4 compatibility ? 
Seems to be a problem with  symfony/http-foundation

Best regards

**Comment by hshn** [comment]
@julienpillias 

Hi, thank you for your reporting.

I've added Symfony 4 support, and now it can be installed as non-stable version `2.x@dev`.
Please check it out.

Thanks.

**Comment by julienpillias** [comment]
Thank's !
Will check end of the week :)

2018-02-13 16:38 GMT+01:00 Shota Hoshino <notifications@github.com>:

**Comment by levacic** [comment]
@hshn Would you mind releasing a new SF4-compatible version as 1.3.0?

**Comment by hshn** [comment]
@levacic I've just released SF4 supported version as [v2.0.0](https://github.com/hshn/base64-encoded-file/releases/tag/v2.0.0)
