### ISSUE TITLE
Composer.json is wrong for dev-master/2.x@dev

### ISSUE THREAD

**Issue by NoMan2000** [hshn/base64-encoded-file#8]
https://semver.mwl.be/#?package=symfony%2Fhttp-foundation&version=~3.0.9%7C%5E4.0.4&minimum-stability=stable

The current way it's written only allows Symfony version 3.0.9

"symfony/http-foundation": "~3.0.9|^4.0.4"

You almost certainly want: 

"symfony/http-foundation": "^3.0.9|^4.0.4"

**Comment by hshn** [comment]
closed via #9
